// Generated by LiveScript 1.3.1
(function(){
  module.exports = function(req, res, next){
    if (req.protocol !== 'https') {
      return res.redirect(['https://', req.get('Host'), req.url].join(''));
    }
    return next();
  };
}).call(this);
